name: Deploy backend on AWS S3

on:
  push:
    branches:
      - main
  

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: cd website/backend && npm install --production

      - name: Package Lambda
        run: cd backend && zip -r ../backend.zip .

      - name: Deploy to Lambda
        run: aws lambda update-function-code \
              --function-name cloudresume-test-api \
              --zip-file fileb://backend.zip

      - name: Verify Lambda
        run: aws lambda invoke \
              --function-name my-backend-function \
              --payload '{}' \
              response.json && cat response.json
                        
                                    

